version: 0.0
os: linux
files:
  - source: application
    destination: /var/www/html/
hooks:
  ApplicationStop:
    - location: scripts/app-stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: scripts/app-start.sh
      timeout: 300
      runas: root